<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro"
  xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
  xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller">

  <property name="sensor_mount_length" value="0.02" />
  <property name="sensor_mount_width" value="0.139" />
  <property name="sensor_mount_height" value="0.189" />
  <property name="sensor_mount_mass" value="0.100" />
  <property name="sensor_mount_x_offset" value="-0.16" />
  <property name="kinect_fixture_length" value="0.02" />
  <property name="kinect_fixture_width" value="0.02" />
  <property name="kinect_fixture_height" value="0.265" />
  <property name="kinect_fixture_mass" value="0.050" />
  <property name="kinect_fixture_x_offset" value="0.00" />
  <property name="kinect_fixture_joint_z_offset" value="-0.015" /> <!-- how much the joint center is displaced from the link center-->
  <property name="laser_z_offset" value="-0.0407" />
  <property name="kinect_x_offset" value="0.0" />
  <property name="kinect_y_offset" value="0.05" />
  <property name="kinect_z_offset" value="0.16" />
  <property name="kinect_r" value="0.0" />
  <property name="kinect_p" value="0.0" />
  <property name="kinect_y" value="-0.07" />
  <property name="pitchpole_radius" value="0.012"/>
  <property name="pitchpole_length" value="0.23"/>
  <property name="pitchpole_mass" value="0.050"/>

  <link name="structure">
    <visual>
      <geometry>
        <!--<box size="0.36 0.32 0.505" />-->
        <mesh filename="package://calvin_description/meshes/item-structure.stl"/>
      </geometry>
      <material name="grey" >
        <color rgba="0.5 0.5 0.5 1" />
      </material>
    </visual>
    <collision>
      <geometry>
        <!-- using STL for collision to fix http://answers.ros.org/question/2368/gazebo-model-wheels-slip-after-upgrade-to-electric -->
        <!--<box size="0.36 0.32 0.505" />-->
        <mesh filename="package://calvin_description/meshes/item-structure.stl"/>
      </geometry>
    </collision>
    <xacro:box_inertial x="0.36" y="0.32" z="0.505" mass="2"/>
  </link>

  <joint name="top_to_structure" type="fixed">
    <parent link="base_link" />
    <child link="structure" />
    <origin xyz="${0.095 - 0.02} 0 ${0.2525 + 0.0775}" rpy="0 0 0" />
  </joint>

  <link name="pole">
    <visual>
      <geometry>
        <!--<box size="0.02 0.02 1.0" />-->
        <mesh filename="package://calvin_description/meshes/item-pole.stl"/>
      </geometry>
      <material name="grey" >
        <color rgba="0.5 0.5 0.5 1" />
      </material>
    </visual>
    <collision>
      <geometry>
        <!-- using STL for collision to fix http://answers.ros.org/question/2368/gazebo-model-wheels-slip-after-upgrade-to-electric -->
        <!--<box size="0.02 0.02 1.0" />-->
        <mesh filename="package://calvin_description/meshes/item-pole.stl"/>
      </geometry>
    </collision>
    <xacro:box_inertial x="0.02" y="0.02" z="1.0" mass="0.25"/>
  </link>

  <joint name="structure_to_pole_joint" type="fixed">
    <parent link="structure" />
    <child link="pole" />
    <origin xyz="${-0.18 - 0.01} 0 ${0.5 + 0.2525 + 0.005}" rpy="0 0 0" />
  </joint>

  <!-- ******************************** -->
  <!-- *** gazebo ros camera plugin *** -->
  <!-- ******************************** -->

  <xacro:macro name="webcam" params="">
    <gazebo reference="webcam">
      <sensor:camera name="webcam">
        <imageFormat>L8</imageFormat>
        <imageSize>640 480</imageSize>
        <hfov>57</hfov>
        <nearClip>0.01</nearClip>
        <farClip>5</farClip>
        <updateRate>1.0</updateRate>
        <baseline>0.2</baseline>
        <controller:gazebo_ros_camera name="webcam_controller" plugin="libgazebo_ros_camera.so">
          <robotNamespace>webcam</robotNamespace>
          <imageTopicName>image_raw</imageTopicName>
          <cameraInfoTopicName>camera_info</cameraInfoTopicName>
          <cameraName>webcam</cameraName>
          <frameName>/world</frameName>
          <updateRate>1</updateRate>
          <CxPrime>10</CxPrime>
          <Cx>10</Cx>
          <Cy>10</Cy>
          <focalLength>10</focalLength>
          <hackBaseline>10</hackBaseline>
          <distortionK1>0</distortionK1>
          <distortionK2>0</distortionK2>
          <distortionK3>0</distortionK3>
          <distortionT1>0</distortionT1>
          <distortionT2>0</distortionT2>
        </controller:gazebo_ros_camera>
      </sensor:camera>
      <material value="Gazebo/Gray" />
    </gazebo>
    <link name="webcam_link">
      <visual>
        <origin rpy="0 0 0" xyz="-0.015 0 0"/>
        <geometry>
          <box size="0.025 0.038 0.038" />
        </geometry>
        <material name="gray">
          <color rgba="0.4 0.4 0.4 1" />
        </material>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <box size="0.03 0.04 0.04" />
        </geometry>
      </collision>
      <xacro:box_inertial x="0.1" y="0.1" z="0.1" mass="0.01"/>
    </link>
    <joint name="webcam_joint" type="fixed">
      <origin xyz="0.07 0 0.35" rpy="0 0.1 0" />
      <parent link="pole" />
      <child link="webcam_link" />
    </joint>
  </xacro:macro>
  <xacro:webcam/>

  <!-- **************************** -->
  <!-- *** Neuronics Katana Arm *** -->
  <!-- **************************** -->

  <include filename="$(find katana_description)/urdf/katana_450_6m90a_with_controlbox.urdf.xacro" />

  <link name="katana_pattern"></link>
  <joint name="katana_pattern_joint" type="fixed">
    <parent link="katana_motor4_lift_link"/>
    <child  link="katana_pattern" />
    <origin xyz=".075 -.035 0.00" rpy="1.571 -1.571 0.151"/>
  </joint>

  <property name="baseplate_height" value="0.006" />
  <joint name="kurtana_baseplate_controlbox_joint" type="fixed">
    <parent link="structure" />
    <child link="katana_internal_controlbox_link" />
    <origin xyz="0 0 ${baseplate_height*1.5 + 0.2525}" rpy="0 0 0" />
  </joint>

  <!-- ********************************** -->
  <!-- *** Kinect / Xtion RGBD Camera *** -->
  <!-- ********************************** -->

  <link name="kinect_pitch_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.08 0.06 0.02" />
      </geometry>
      <material name="grey">
        <color rgba="0.5 0.5 0.5 1" />
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.08 0.06 0.02" />
      </geometry>
    </collision>
    <xacro:box_inertial x="0.08" y="0.06" z="0.02" mass="0.01"/>
  </link>

  <joint name="kinect_pitch_joint" type="revolute">
    <parent link="pole" />
    <child link="kinect_pitch_link" />
    <origin xyz="0.025 0 0.46" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="${-M_PI/2}" upper="${M_PI/2}" velocity="2.0"/>
  </joint>

  <include filename="$(find uos_common_urdf)/urdf/kinect.urdf.xacro" />
  <xacro:kinect camera="kinect" />

  <joint name="calvin_kinect_joint" type="fixed">
    <parent link="kinect_pitch_link" />
    <child  link="kinect_link" />
    <origin xyz="0.03 0.03 0.02" rpy="0 0 0"/>
  </joint>

  <xacro:macro name="kinect_pole_transmission" params="name">
    <transmission name="${name}_trans" type="pr2_mechanism_model/SimpleTransmission">
      <actuator name="${name}_motor" />
      <joint name="${name}_joint" />
      <mechanicalReduction>1</mechanicalReduction>
      <motorTorqueConstant>1</motorTorqueConstant>
    </transmission>
  </xacro:macro>

  <xacro:kinect_pole_transmission name="kinect_pitch" />
</robot>
