scan_filter_chain:
- name: shadows2
  type: ScanShadowsFilter
  params:
    min_angle: 10
    max_angle: 170 
    neighbors: 1
    window: 1
- name: footprint_filter2
  type: LaserScanFootprintFilter
  params: 
    inscribed_radius: 0.34
