scan_filter_chain:
- name: footprint_filter
  type: LaserScanFootprintFilter
  params: 
    inscribed_radius: 0.34

- type: LaserArrayFilter
  name: laser_median_filter
  params:
    range_filter_chain:
      - name: median_5
        type: MultiChannelMedianFilterFloat
        params: 
          number_of_observations: 5
          unused: 10
    intensity_filter_chain:
      - name: median_5
        type: MultiChannelMedianFilterFloat
        params: 
          number_of_observations: 5
          unused: 10
